import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <div className="flex flex-col h-screen">
          <div className="flex flex-1 h-[90%]">

            <aside className="w-1/4 p-6 sm:w-60 bg-gray-800 text-gray-100">
              <nav className="space-y-8 text-sm">
                <div className="space-y-2">
                  <h2 className="text-sm font-semibold tracking-widest uppercase dark:text-gray-600">Getting Started</h2>
                  <div className="flex flex-col space-y-1">
                    <a rel="noopener noreferrer" href="#">Installation</a>
                    <a rel="noopener noreferrer" href="#">Plugins</a>
                    <a rel="noopener noreferrer" href="#">Migrations</a>
                    <a rel="noopener noreferrer" href="#">Appearance</a>
                    <a rel="noopener noreferrer" href="#">Mamba UI</a>
                  </div>
                </div>
                <div className="space-y-2">
                  <h2 className="text-sm font-semibold tracking-widest uppercase dark:text-gray-600">Dashboard</h2>
                  <div className="flex flex-col space-y-1">
                    <a rel="noopener noreferrer" href="#">Header</a>
                    <a rel="noopener noreferrer" href="#">Drawer</a>
                    <a rel="noopener noreferrer" href="#">Page Title</a>
                    <a rel="noopener noreferrer" href="#">Menus</a>
                    <a rel="noopener noreferrer" href="#">Sidebar</a>
                    <a rel="noopener noreferrer" href="#">Footer</a>
                  </div>
                </div>
                <div className="space-y-2">
                  <h2 className="text-sm font-semibold tracking-widest uppercase dark:text-gray-600">Pages</h2>
                  <div className="flex flex-col space-y-1">
                    <a rel="noopener noreferrer" href="#">Homepage</a>
                    <a rel="noopener noreferrer" href="#">Users</a>
                    <a rel="noopener noreferrer" href="#">Tools</a>
                    <a rel="noopener noreferrer" href="#">Settings</a>
                  </div>
                </div>
              </nav>
            </aside>
            <div>
              <header className="flex-1 fixed top-0 h-24 p-4 w-full bg-gray-800 text-gray-100">
                <div className="container flex justify-between h-16 mx-auto">
                  <a rel="noopener noreferrer" href="#" aria-label="Back to homepage" className="flex items-center p-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 32 32" className="w-8 h-8 dark:text-violet-600">
                      <path d="M27.912 7.289l-10.324-5.961c-0.455-0.268-1.002-0.425-1.588-0.425s-1.133 0.158-1.604 0.433l0.015-0.008-10.324 5.961c-0.955 0.561-1.586 1.582-1.588 2.75v11.922c0.002 1.168 0.635 2.189 1.574 2.742l0.016 0.008 10.322 5.961c0.455 0.267 1.004 0.425 1.59 0.425 0.584 0 1.131-0.158 1.602-0.433l-0.014 0.008 10.322-5.961c0.955-0.561 1.586-1.582 1.588-2.75v-11.922c-0.002-1.168-0.633-2.189-1.573-2.742zM27.383 21.961c0 0.389-0.211 0.73-0.526 0.914l-0.004 0.002-10.324 5.961c-0.152 0.088-0.334 0.142-0.53 0.142s-0.377-0.053-0.535-0.145l0.005 0.002-10.324-5.961c-0.319-0.186-0.529-0.527-0.529-0.916v-11.922c0-0.389 0.211-0.73 0.526-0.914l0.004-0.002 10.324-5.961c0.152-0.090 0.334-0.143 0.53-0.143s0.377 0.053 0.535 0.144l-0.006-0.002 10.324 5.961c0.319 0.185 0.529 0.527 0.529 0.916z"></path>
                      <path d="M22.094 19.451h-0.758c-0.188 0-0.363 0.049-0.515 0.135l0.006-0.004-4.574 2.512-5.282-3.049v-6.082l5.282-3.051 4.576 2.504c0.146 0.082 0.323 0.131 0.508 0.131h0.758c0.293 0 0.529-0.239 0.529-0.531v-0.716c0-0.2-0.11-0.373-0.271-0.463l-0.004-0.002-5.078-2.777c-0.293-0.164-0.645-0.26-1.015-0.26-0.39 0-0.756 0.106-1.070 0.289l0.010-0.006-5.281 3.049c-0.636 0.375-1.056 1.055-1.059 1.834v6.082c0 0.779 0.422 1.461 1.049 1.828l0.009 0.006 5.281 3.049c0.305 0.178 0.67 0.284 1.061 0.284 0.373 0 0.723-0.098 1.027-0.265l-0.012 0.006 5.080-2.787c0.166-0.091 0.276-0.265 0.276-0.465v-0.716c0-0.293-0.238-0.529-0.529-0.529z"></path>
                    </svg>
                  </a>
                  <ul className="items-stretch hidden space-x-3 lg:flex">
                    <li className="flex">
                      <a rel="noopener noreferrer" href="#" className="flex items-center px-4 -mb-1 border-b-2 dark:border- dark:text-violet-600 dark:border-violet-600">Link</a>
                    </li>
                    <li className="flex">
                      <a rel="noopener noreferrer" href="#" className="flex items-center px-4 -mb-1 border-b-2 dark:border-">Link</a>
                    </li>
                    <li className="flex">
                      <a rel="noopener noreferrer" href="#" className="flex items-center px-4 -mb-1 border-b-2 dark:border-">Link</a>
                    </li>
                    <li className="flex">
                      <a rel="noopener noreferrer" href="#" className="flex items-center px-4 -mb-1 border-b-2 dark:border-">Link</a>
                    </li>
                  </ul>
                  
                  <div className="items-center flex-shrink-0 hidden lg:flex">
                    <Link className="self-center px-8 py-3 rounded" href="/user/signin">Login</Link>
                    <Link className="self-center px-8 py-3 font-semibold rounded dark:bg-violet-600 dark:text-gray-50" href="/user/register">Register</Link>
                  </div>
                  <button className="p-4 lg:hidden">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" className="w-6 h-6 dark:text-gray-800">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                  </button>
                </div>
              </header>
              <div className="flex-1 h-full overflow-y-auto">{children}</div>
            </div>
          </div>

          <footer className="h-[10%] bg-gray-800 text-gray-100">
            <div className="container flex flex-col p-4 mx-auto md:p-8 lg:flex-row dark:divide-gray-600 !pb-0">
              <ul className="self-center py-6 space-y-4 text-center sm:flex sm:space-y-0 sm:justify-around sm:space-x-4 lg:flex-1 lg:justify-start">
                <li>Shop</li>
                <li>About</li>
                <li>Blog</li>
                <li>Pricing</li>
                <li>Contact</li>
              </ul>
              <div className="flex flex-col justify-center pt-6 lg:pt-0">
                <div className="flex justify-center space-x-4">
                  {/* Social Media Icons */}
                  <a rel="noopener noreferrer" href="#" title="Instagram" className="flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 dark:bg-violet-600 dark:text-gray-50">
                    {/* SVG Icon */}
                  </a>
                  <a rel="noopener noreferrer" href="#" title="Pinterest" className="flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 dark:bg-violet-600 dark:text-gray-50">
                    {/* SVG Icon */}
                  </a>
                  <a rel="noopener noreferrer" href="#" title="Twitter" className="flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 dark:bg-violet-600 dark:text-gray-50">
                    {/* SVG Icon */}
                  </a>
                  <a rel="noopener noreferrer" href="#" title="Facebook" className="flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 dark:bg-violet-600 dark:text-gray-50">
                    {/* SVG Icon */}
                  </a>
                  <a rel="noopener noreferrer" href="#" title="Gmail" className="flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 dark:bg-violet-600 dark:text-gray-50">
                    {/* SVG Icon */}
                  </a>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
